/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Tutorial",
      items: ["intro"],
    },
    {
      type: "category",
      label: "Tutorial-Basic",
      items: [
        "tutorial-basics/congratulations",
        "tutorial-basics/create-a-blog-post",
        "tutorial-basics/create-a-document",
        "tutorial-basics/create-a-page",
        "tutorial-basics/deploy-your-site",
        "tutorial-basics/markdown-features",
      ],
    },
    {
      type: "autogenerated",
      dirName: "tutorial-extras",
    },
  ],
  docsSidebar: [
    {
      type: "category",
      label: "Getting started",
      items: ["documentation/getting-started"],
    },
    {
      type: "category",
      label: "The PeakLeap Platform",
      items: [
        "documentation/peakleap-platform/admin",
        "documentation/peakleap-platform/profile",
        {
          type: "category",
          label: "Settings",
          items: [
            "documentation/peakleap-platform/settings-dashboard", 
            "documentation/peakleap-platform/settings-profile",
            "documentation/peakleap-platform/settings-billing",
            "documentation/peakleap-platform/settings-merchant",
            "documentation/peakleap-platform/settings-referrals",
            "documentation/peakleap-platform/settings-settings",
          ],
        },
        "documentation/peakleap-platform/organization",
        "documentation/peakleap-platform/issue-credentials",
      ],
    },
    {
      type: "category",
      label: "Courses",
      items: [
        "documentation/courses/create-a-new-course",
        {
          type: "category",
          label: "Edit course",
          items: [
            "documentation/courses/settings",
            "documentation/courses/participants",
            "documentation/courses/sections",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Programs",
      items: [
        "documentation/programs/create-new-program",
        "documentation/programs/edit-program",
      ],
    },
    {
      type: "category",
      label: "Credentials",
      items: [
        "documentation/credentials/batch-issue",
        "documentation/credentials/issue-credential",
      ],
    },
    {
      type: "category",
      label: "Assessments",
      items: [
        "documentation/assessments/create-new-assessment",
        "documentation/assessments/participants",
        "documentation/assessments/questions",
        "documentation/assessments/settings",
      ],
    },
  ],
};

module.exports = sidebars;
